import { parse } from "@babel/parser";
import type { ClassMethod } from "@babel/types";
import type { ElementNode, ForNode, IfBranchNode, IfNode, RootNode, TemplateChildNode } from "@vue/compiler-core";
import { NodeTypes, parse as parseTemplate } from "@vue/compiler-dom";
import { parse as parseSfc } from "@vue/compiler-sfc";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { generateViewObjectModelMethodContent } from "../method-generation";
import { introspectNuxtPages, parseRouterFileFromCwd } from "../router-introspection";
import {
  IComponentDependencies,
  IDataTestId,
  PomExtraClickMethodSpec,
  PomPrimarySpec,
  isAsciiAlphaNumericCode,
  isAsciiUppercaseLetterCode,
  upperFirst,
} from "../utils";

// Intentionally imported so tooling understands this exported helper is part of the
// generated POM public surface (it is consumed by generated Playwright fixtures).
import { setPlaywrightAnimationOptions } from "./Pointer";

void setPlaywrightAnimationOptions;

export { generateViewObjectModelMethodContent };

const AUTO_GENERATED_COMMENT
  = " * DO NOT MODIFY BY HAND\n"
    + " *\n"
    + " * This file is auto-generated by vue-pom-generator.\n"
    + " * Changes should be made in the generator/template, not in the generated output.\n"
    + " */";
const GENERATED_GITATTRIBUTES_BLOCK_START = "# BEGIN vue-pom-generator generated files";
const GENERATED_GITATTRIBUTES_BLOCK_END = "# END vue-pom-generator generated files";
const eslintSuppressionHeader = "/* eslint-disable perfectionist/sort-imports */\n";
const VUE_POM_GENERATOR_ERROR_PREFIX = "[vue-pom-generator]" as const;

class VuePomGeneratorError extends Error {
  public constructor(message: string) {
    const normalized = message.startsWith(VUE_POM_GENERATOR_ERROR_PREFIX)
      ? message
      : `${VUE_POM_GENERATOR_ERROR_PREFIX} ${message}`;
    super(normalized);
    this.name = "VuePomGeneratorError";
  }
}

function toPosixRelativePath(fromDir: string, toFile: string): string {
  let rel = path.relative(fromDir, toFile).replace(/\\/g, "/");
  if (!rel.startsWith(".")) {
    rel = `./${rel}`;
  }
  return rel;
}

function stripExtension(filePath: string): string {
  // IMPORTANT:
  // This helper is used for generating *import specifiers*.
  // On Windows, `path.parse/path.format` can re-introduce backslashes even when
  // the input contains `/` separators, producing invalid TS string escapes like `"..\\pom\\custom\\nGrid"`.
  // Keep these paths POSIX-normalized.
  const posix = (filePath ?? "").replace(/\\/g, "/");
  const parsed = path.posix.parse(posix);
  return path.posix.format({ ...parsed, base: parsed.name, ext: "" });
}

function resolveRouterEntry(projectRoot?: string, routerEntry?: string) {
  if (!routerEntry) {
    throw new Error("[vue-pom-generator] Router entry path is required when routerAwarePoms is enabled.");
  }
  const root = projectRoot ?? process.cwd();
  return path.isAbsolute(routerEntry) ? routerEntry : path.resolve(root, routerEntry);
}

interface RouteMeta {
  template: string;
}

interface CustomPomMethodSignature {
  params: string;
  argNames: string[];
}

type CustomPomMethodSignatureMap = Map<string, CustomPomMethodSignature>;

interface CustomPomAttachment {
  className: string;
  propertyName: string;
  attachWhenUsesComponents: string[];
  attachTo?: "views" | "components" | "both" | "pagesAndComponents";
  flatten?: boolean;
}

interface ResolvedCustomPomAttachment {
  className: string;
  propertyName: string;
  flatten: boolean;
  methodSignatures: CustomPomMethodSignatureMap;
}

export type TypeScriptOutputStructure = "aggregated" | "split";

interface ResolvedCustomPomImportSpecifier {
  exportName: string;
  localIdentifier: string;
  absolutePath: string;
}

interface CustomPomImportResolution {
  classIdentifierMap: Record<string, string>;
  methodSignaturesByClass: Map<string, CustomPomMethodSignatureMap>;
  availableClassIdentifiers: Set<string>;
  importSpecifiersByClass: Record<string, ResolvedCustomPomImportSpecifier>;
}

function createCustomPomImportCollisionError(exportName: string, requested: string): VuePomGeneratorError {
  return new VuePomGeneratorError(
    `Custom POM import name collision detected for "${exportName}".\n`
    + `The identifier "${requested}" conflicts with a generated POM class.\n`
    + `Fix by setting generation.playwright.customPoms.importAliases["${exportName}"] to a unique name, `
    + `or set generation.playwright.customPoms.importNameCollisionBehavior = "alias" to auto-alias collisions.`,
  );
}

function isPascalCaseComponentTag(tag: string): boolean {
  if (!tag) {
    return false;
  }

  const first = tag.charCodeAt(0);
  if (!isAsciiUppercaseLetterCode(first)) {
    return false;
  }

  for (let i = 1; i < tag.length; i += 1) {
    const code = tag.charCodeAt(i);
    if (isAsciiAlphaNumericCode(code) || tag[i] === "_") {
      continue;
    }
    return false;
  }

  return true;
}

function collectPascalCaseComponentTags(nodes: readonly TemplateChildNode[], names: Set<string>): void {
  for (const node of nodes) {
    switch (node.type) {
      case NodeTypes.ELEMENT: {
        const element = node as ElementNode;
        if (isPascalCaseComponentTag(element.tag)) {
          names.add(element.tag);
        }
        collectPascalCaseComponentTags(element.children, names);
        break;
      }
      case NodeTypes.IF: {
        const ifNode = node as IfNode;
        for (const branch of ifNode.branches) {
          collectPascalCaseComponentTags((branch as IfBranchNode).children, names);
        }
        break;
      }
      case NodeTypes.FOR: {
        const forNode = node as ForNode;
        collectPascalCaseComponentTags(forNode.children, names);
        break;
      }
      default:
        break;
    }
  }
}

function getPascalCaseComponentTagsFromVueSource(source: string): string[] {
  try {
    const { descriptor } = parseSfc(source);
    const template = descriptor.template?.content?.trim();
    if (!template) {
      return [];
    }

    const root = parseTemplate(template) as RootNode;
    const names = new Set<string>();
    collectPascalCaseComponentTags(root.children, names);
    return [...names];
  }
  catch {
    return [];
  }
}

function resolveVueSourcePath(
  targetClassName: string,
  vueFilesPathMap: Map<string, string>,
  projectRoot: string,
): string | undefined {
  const mapped = vueFilesPathMap.get(targetClassName);
  const candidates = [
    mapped,
    path.join(projectRoot, "src", "views", `${targetClassName}.vue`),
    path.join(projectRoot, "src", "components", `${targetClassName}.vue`),
  ].filter((candidate): candidate is string => typeof candidate === "string" && candidate.length > 0);

  return candidates.find(candidate => fs.existsSync(candidate));
}

async function getRouteMetaByComponent(
  projectRoot?: string,
  routerEntry?: string,
  routerType?: "vue-router" | "nuxt",
  options: {
    viewsDir?: string;
    scanDirs?: string[];
  } = {},
): Promise<Record<string, RouteMeta>> {
  const root = projectRoot ?? process.cwd();
  const viewsDir = options.viewsDir ?? "src/views";
  const viewsDirAbs = path.isAbsolute(viewsDir) ? viewsDir : path.resolve(root, viewsDir);
  const scanDirs = options.scanDirs?.length ? options.scanDirs : ["src"];
  const extraRoots = process.cwd() !== root ? [process.cwd()] : [];

  const { routeMetaEntries } = routerType === "nuxt"
    ? await introspectNuxtPages(root)
    : await parseRouterFileFromCwd(resolveRouterEntry(root, routerEntry), {
      componentNaming: {
        projectRoot: root,
        viewsDirAbs,
        scanDirs,
        extraRoots,
      },
    });

  const map = new Map<string, RouteMeta[]>();
  for (const entry of routeMetaEntries) {
    const list = map.get(entry.componentName) ?? [];
    list.push({ template: entry.pathTemplate });
    map.set(entry.componentName, list);
  }

  const chooseRouteMeta = (entries: RouteMeta[]): RouteMeta | null => {
    if (!entries.length)
      return null;
    return entries
      .slice()
      .sort((a, b) => a.template.length - b.template.length || a.template.localeCompare(b.template))[0];
  };

  const sorted = Array.from(map.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  return Object.fromEntries(
    sorted
      .map(([componentName, entries]) => {
        const chosen = chooseRouteMeta(entries);
        return chosen ? [componentName, chosen] : null;
      })
      .filter((entry): entry is [string, RouteMeta] => !!entry),
  );
}

function generateRouteProperty(routeMeta: RouteMeta | null): string {
  if (!routeMeta) {
    return "    static readonly route: { template: string } | null = null;\n";
  }

  return [
    "    static readonly route: { template: string } | null = {",
    `        template: ${JSON.stringify(routeMeta.template)},`,
    "    } as const;",
    "",
  ].join("\n");
}

function generateGoToSelfMethod(componentName: string): string {
  return [
    "",
    "    async goTo() {",
    "        await this.goToSelf();",
    "    }",
    "",
    "    async goToSelf() {",
    `        const route = ${componentName}.route;`,
    "        if (!route) {",
    `            throw new Error("[pom] No router path found for component/page-object '${componentName}'.");`,
    "        }",
    "        const runtimeEnv = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;",
    "        const runtimeBaseUrl = runtimeEnv?.PLAYWRIGHT_RUNTIME_BASE_URL ?? runtimeEnv?.PLAYWRIGHT_TEST_BASE_URL ?? runtimeEnv?.VITE_PLAYWRIGHT_BASE_URL;",
    "        const targetUrl = runtimeBaseUrl ? new URL(route.template, runtimeBaseUrl).toString() : route.template;",
    "        await this.page.goto(targetUrl);",
    "    }",
    "",
  ].join("\n");
}

function formatMethodParams(params: Record<string, string> | undefined): string {
  if (!params)
    return "";

  // Keep output stable and somewhat intuitive.
  const preferredOrder = ["key", "value", "text", "timeOut", "annotationText", "wait"];

  const entries = Object.entries(params);
  if (!entries.length)
    return "";

  const score = (name: string) => {
    const idx = preferredOrder.indexOf(name);
    return idx < 0 ? 999 : idx;
  };

  return entries
    .slice()
    .sort((a, b) => score(a[0]) - score(b[0]) || a[0].localeCompare(b[0]))
    .map(([name, typeExpr]) => `${name}: ${typeExpr}`)
    .join(", ");
}

function generateExtraClickMethodContent(spec: PomExtraClickMethodSpec): string {
  if (spec.kind !== "click") {
    return "";
  }

  const params = spec.params ?? {};
  const signatureParams = formatMethodParams(params);
  const signature = signatureParams ? `(${signatureParams})` : "()";

  const lines: string[] = [];
  lines.push(
    "",
    `    async ${spec.name}${signature} {`,
  );

  if (spec.keyLiteral !== undefined) {
    lines.push(`        const key = ${JSON.stringify(spec.keyLiteral)};`);
  }

  const hasAnnotationText = Object.prototype.hasOwnProperty.call(params, "annotationText");
  const hasWait = Object.prototype.hasOwnProperty.call(params, "wait");
  const annotationArg = hasAnnotationText ? "annotationText" : "\"\"";
  const waitArg = hasWait ? "wait" : "true";

  if (spec.selector.kind === "testId") {
    const needsTemplate = spec.selector.formattedDataTestId.includes("${");
    const testIdExpr = needsTemplate
      ? `\`${spec.selector.formattedDataTestId}\``
      : JSON.stringify(spec.selector.formattedDataTestId);

    if (needsTemplate) {
      lines.push(`        const testId = ${testIdExpr};`);
    }

    const clickArgs: string[] = [];
    clickArgs.push(needsTemplate ? "testId" : testIdExpr);

    if (hasAnnotationText || hasWait) {
      clickArgs.push(annotationArg);
    }
    if (hasWait) {
      clickArgs.push(waitArg);
    }

    lines.push(`        await this.clickByTestId(${clickArgs.join(", ")});`);
    lines.push("    }");

    return `${lines.join("\n")}\n`;
  }

  const rootNeedsTemplate = spec.selector.rootFormattedDataTestId.includes("${");
  const labelNeedsTemplate = spec.selector.formattedLabel.includes("${");
  const rootExpr = rootNeedsTemplate
    ? `\`${spec.selector.rootFormattedDataTestId}\``
    : JSON.stringify(spec.selector.rootFormattedDataTestId);
  const labelExpr = labelNeedsTemplate
    ? `\`${spec.selector.formattedLabel}\``
    : JSON.stringify(spec.selector.formattedLabel);

  if (rootNeedsTemplate) {
    lines.push(`        const rootTestId = ${rootExpr};`);
  }
  if (labelNeedsTemplate) {
    lines.push(`        const label = ${labelExpr};`);
  }
  const rootArg = rootNeedsTemplate ? "rootTestId" : rootExpr;
  const labelArg = labelNeedsTemplate ? "label" : labelExpr;
  lines.push(`        await this.clickWithinTestIdByLabel(${rootArg}, ${labelArg}, ${annotationArg}, ${waitArg});`);
  lines.push("    }");

  return `${lines.join("\n")}\n`;
}

function generateMethodContentFromPom(primary: PomPrimarySpec, targetPageObjectModelClass?: string): string {
  if (primary.emitPrimary === false) {
    return "";
  }

  return generateViewObjectModelMethodContent(
    targetPageObjectModelClass,
    primary.methodName,
    primary.nativeRole,
    primary.formattedDataTestId,
    primary.alternateFormattedDataTestIds,
    primary.getterNameOverride,
    primary.params ?? {},
  );
}

function generateMethodsContentForDependencies(dependencies: IComponentDependencies): string {
  const entries = Array.from(dependencies.dataTestIdSet ?? []);
  const primarySpecsAll = entries
    .map(e => ({ pom: e.pom, target: e.targetPageObjectModelClass }))
    .filter((x): x is { pom: PomPrimarySpec; target: string | undefined } => !!x.pom)
    .sort((a, b) => a.pom.methodName.localeCompare(b.pom.methodName));

  // IMPORTANT:
  // `dependencies.dataTestIdSet` is a Set of objects; it does not de-dupe by semantic identity.
  // It's possible to end up with multiple IDataTestId entries that carry identical `pom` specs.
  // When we emit from IR, we must de-dupe here to avoid duplicate getters/methods.
  const seenPrimaryKeys = new Set<string>();
  const primarySpecs = primarySpecsAll.filter(({ pom, target }) => {
    const stableParams = pom.params
      ? Object.fromEntries(Object.entries(pom.params).sort((a, b) => a[0].localeCompare(b[0])))
      : undefined;
    const alternates = (pom.alternateFormattedDataTestIds ?? []).slice().sort();
    const key = JSON.stringify({
      role: pom.nativeRole,
      methodName: pom.methodName,
      getterNameOverride: pom.getterNameOverride ?? null,
      testId: pom.formattedDataTestId,
      alternateTestIds: alternates.length ? alternates : undefined,
      params: stableParams,
      target: target ?? null,
      emitPrimary: pom.emitPrimary ?? true,
    });
    if (seenPrimaryKeys.has(key)) {
      return false;
    }
    seenPrimaryKeys.add(key);
    return true;
  });

  const extras = (dependencies.pomExtraMethods ?? [])
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name));

  let content = "";
  for (const { pom, target } of primarySpecs) {
    content += generateMethodContentFromPom(pom, target);
  }

  for (const extra of extras) {
    content += generateExtraClickMethodContent(extra);
  }

  return content;
}

export interface GenerateFilesOptions {
  /**
   * Output directory for generated files.
   *
   * Defaults to `./pom` when omitted (backwards compatible default for internal usage).
   */
  outDir?: string;

  /**
   * Generate Playwright fixture helpers alongside generated POMs.
   *
   * Default output (when `true`):
   * - `<projectRoot>/<outDir>/fixtures.g.ts`
   *
   * Convention:
   * - fixtures automatically prefer matching handwritten override classes from
   *   `<dirname(customPomDir)>/overrides/<ClassName>.ts` when present
   *
   * Accepted values:
   * - `true`: enable with defaults
   * - `"path"`: enable and write the fixture file under this directory (resolved relative to projectRoot),
   *   or to this file path if it ends with `.ts`/`.tsx`/`.mts`/`.cts`
   * - `{ outDir }`: enable and override where fixture files are written (resolved relative to projectRoot)
   */
  generateFixtures?: boolean | string | { outDir?: string };

  /**
   * Project root used for resolving conventional paths (e.g. src/views, tests/playwright/pom/custom).
   * Defaults to process.cwd() for backwards compatibility.
   */
  projectRoot?: string;

  /**
   * Directory containing handwritten POM helpers to import into aggregated output.
   * Defaults to <projectRoot>/tests/playwright/pom/custom.
   */
  customPomDir?: string;

  /**
   * Optional import aliases for handwritten POM helpers.
   *
   * Keyed by the helper file/export name (basename of the .ts file).
   * Value is the identifier to import it as.
   *
   * Example: { Toggle: "ToggleWidget" }
   */
  customPomImportAliases?: Record<string, string>;

  /**
   * How to handle collisions between custom POM import identifiers and generated class names.
   *
   * - "error" (default): fail generation with a descriptive error
   * - "alias": auto-alias colliding custom imports (e.g. PersonListPage -> PersonListPageCustom)
   */
  customPomImportNameCollisionBehavior?: "error" | "alias";

  /**
   * Handwritten POM helper attachments. These helpers are assumed to be present in the
   * aggregated output (e.g. via `tests/playwright/pom/custom/*.ts` inlining), but we only attach them to
   * view classes that actually use certain components.
   */
  customPomAttachments?: CustomPomAttachment[];

  /** Attribute name to treat as the test id. Defaults to `data-testid`. */
  testIdAttribute?: string;

  /** Which POM languages to emit. Defaults to ["ts"]. */
  emitLanguages?: Array<"ts" | "csharp">;

  /**
   * Controls how TypeScript Playwright page objects are emitted.
   *
   * - "aggregated" (default): emit a single `page-object-models.g.ts`
   * - "split": emit one generated `.g.ts` file per class plus a stable `index.ts` barrel
   */
  typescriptOutputStructure?: TypeScriptOutputStructure;

  /** C# generation options. */
  csharp?: {
    namespace?: string;
  };

  /** When true, generate router-aware helpers like goToSelf() on view POMs. */
  vueRouterFluentChaining?: boolean;

  /** Router entry path used for vue-router introspection when fluent chaining is enabled. */
  routerEntry?: string;

  /** The type of router introspection to perform. */
  routerType?: "vue-router" | "nuxt";

  viewsDir?: string;
  scanDirs?: string[];

  routeMetaByComponent?: Record<string, RouteMeta>;
}

interface BaseGenerateContentOptions {
  /** Directory the generated .g.ts file will live in (used for relative imports). Defaults to the Vue file's directory. */
  outputDir?: string;

  customPomAttachments?: CustomPomAttachment[];

  projectRoot?: string;
  customPomDir?: string;
  customPomImportAliases?: Record<string, string>;
  customPomClassIdentifierMap?: Record<string, string>;
  customPomAvailableClassIdentifiers?: Set<string>;
  customPomImportSpecifiersByClass?: Record<string, ResolvedCustomPomImportSpecifier>;
  customPomMethodSignaturesByClass?: Map<string, CustomPomMethodSignatureMap>;
  generatedTsFilePathByComponent?: Map<string, string>;

  /** Attribute name to treat as the test id. Defaults to `data-testid`. */
  testIdAttribute?: string;

  /** When true, generate router-aware helpers like goToSelf() on view POMs. */
  vueRouterFluentChaining?: boolean;

  routeMetaByComponent?: Record<string, RouteMeta>;
}

type GenerateContentOptions
  = BaseGenerateContentOptions & (
    { outputStructure: "aggregated" }
    | { outputStructure?: "split" }
  );

interface GeneratedFileOutput {
  filePath: string;
  content: string;
}

export async function generateFiles(
  componentHierarchyMap: Map<string, IComponentDependencies>,
  vueFilesPathMap: Map<string, string>,
  basePageClassPath: string,
  options: GenerateFilesOptions = {},
) {
  const {
    outDir: outDirOverride,
    generateFixtures,
    customPomAttachments = [],
    projectRoot,
    customPomDir,
    customPomImportAliases,
    customPomImportNameCollisionBehavior = "error",
    testIdAttribute,
    emitLanguages: emitLanguagesOverride,
    typescriptOutputStructure = "aggregated",
    csharp,
    vueRouterFluentChaining,
    routerEntry,
    routerType,
    viewsDir,
    scanDirs,
    routeMetaByComponent: routeMetaByComponentOverride,
  } = options;

  const emitLanguages: Array<"ts" | "csharp"> = emitLanguagesOverride?.length
    ? emitLanguagesOverride
    : ["ts"];

  const outDir = outDirOverride ?? "./pom";

  const routeMetaByComponent = routeMetaByComponentOverride
    ?? (vueRouterFluentChaining
      ? await getRouteMetaByComponent(projectRoot, routerEntry, routerType, {
        viewsDir,
        scanDirs,
      })
      : undefined);
  const generatedFilePaths: string[] = [];
  const writeGeneratedFile = (file: GeneratedFileOutput) => {
    const resolvedFilePath = path.resolve(file.filePath);
    createFile(resolvedFilePath, file.content);
    generatedFilePaths.push(resolvedFilePath);
  };

  if (emitLanguages.includes("ts")) {
    const files = typescriptOutputStructure === "split"
      ? await generateSplitTypeScriptFiles(componentHierarchyMap, vueFilesPathMap, basePageClassPath, outDir, {
        customPomAttachments,
        projectRoot,
        customPomDir,
        customPomImportAliases,
        customPomImportNameCollisionBehavior,
        testIdAttribute,
        routeMetaByComponent,
        vueRouterFluentChaining,
      })
      : await generateAggregatedFiles(componentHierarchyMap, vueFilesPathMap, basePageClassPath, outDir, {
        customPomAttachments,
        projectRoot,
        customPomDir,
        customPomImportAliases,
        customPomImportNameCollisionBehavior,
        testIdAttribute,
        generateFixtures,
        routeMetaByComponent,
        vueRouterFluentChaining,
      });
    for (const file of files) {
      writeGeneratedFile(file);
    }

    const fixtureRegistryFile = maybeGenerateFixtureRegistry(componentHierarchyMap, {
      generateFixtures,
      pomOutDir: outDir,
      projectRoot,
      customPomDir,
    });
    if (fixtureRegistryFile) {
      writeGeneratedFile(fixtureRegistryFile);
    }
  }

  if (emitLanguages.includes("csharp")) {
    const csFiles = generateAggregatedCSharpFiles(componentHierarchyMap, outDir, {
      projectRoot,
      testIdAttribute,
      csharp,
    });
    for (const file of csFiles) {
      writeGeneratedFile(file);
    }
  }

  const gitattributesFiles = buildGeneratedGitAttributesFiles(generatedFilePaths);
  for (const file of gitattributesFiles) {
    createFile(file.filePath, file.content);
  }
}

async function generateSplitTypeScriptFiles(
  componentHierarchyMap: Map<string, IComponentDependencies>,
  vueFilesPathMap: Map<string, string>,
  basePageClassPath: string,
  outDir: string,
  options: {
    customPomAttachments?: GenerateFilesOptions["customPomAttachments"];
    projectRoot?: GenerateFilesOptions["projectRoot"];
    customPomDir?: GenerateFilesOptions["customPomDir"];
    customPomImportAliases?: GenerateFilesOptions["customPomImportAliases"];
    customPomImportNameCollisionBehavior?: GenerateFilesOptions["customPomImportNameCollisionBehavior"];
    testIdAttribute?: GenerateFilesOptions["testIdAttribute"];
    routeMetaByComponent?: Record<string, RouteMeta>;
    vueRouterFluentChaining?: boolean;
  } = {},
): Promise<GeneratedFileOutput[]> {
  const projectRoot = options.projectRoot ?? process.cwd();
  const entries = Array.from(componentHierarchyMap.entries())
    .sort((a, b) => a[0].localeCompare(b[0]));

  const base = ensureDir(outDir);
  const generatedClassNames = new Set(entries.map(([name]) => name));
  const referencedTargets = new Set<string>();
  for (const [, deps] of entries) {
    for (const dataTestId of deps.dataTestIdSet ?? []) {
      if (dataTestId.targetPageObjectModelClass) {
        referencedTargets.add(dataTestId.targetPageObjectModelClass);
      }
    }
  }

  const stubTargets = Array.from(referencedTargets)
    .filter(target => !generatedClassNames.has(target))
    .sort((a, b) => a.localeCompare(b));

  const availableClassNames = new Set<string>([...generatedClassNames, ...stubTargets]);
  const depsByClassName = new Map<string, IComponentDependencies>(entries);
  const generatedTsFilePathByComponent = new Map<string, string>();
  for (const className of availableClassNames) {
    generatedTsFilePathByComponent.set(className, path.join(base, `${className}.g.ts`));
  }

  const customPomImportResolution = resolveCustomPomImportResolution(generatedClassNames, projectRoot, {
    customPomDir: options.customPomDir,
    customPomImportAliases: options.customPomImportAliases,
    customPomImportNameCollisionBehavior: options.customPomImportNameCollisionBehavior,
  });

  const runtimeBasePagePath = path.join(base, "_pom-runtime", "class-generation", "BasePage.ts");
  const files: GeneratedFileOutput[] = [];

  for (const [name, deps] of entries) {
    const filePath = generatedTsFilePathByComponent.get(name);
    if (!filePath) {
      continue;
    }

    const content = generateViewObjectModelContent(name, deps, componentHierarchyMap, vueFilesPathMap, runtimeBasePagePath, {
      outputDir: path.dirname(filePath),
      outputStructure: "split",
      customPomAttachments: options.customPomAttachments ?? [],
      projectRoot,
      customPomDir: options.customPomDir,
      customPomImportAliases: options.customPomImportAliases,
      customPomClassIdentifierMap: customPomImportResolution.classIdentifierMap,
      customPomAvailableClassIdentifiers: customPomImportResolution.availableClassIdentifiers,
      customPomImportSpecifiersByClass: customPomImportResolution.importSpecifiersByClass,
      customPomMethodSignaturesByClass: customPomImportResolution.methodSignaturesByClass,
      generatedTsFilePathByComponent,
      testIdAttribute: options.testIdAttribute,
      vueRouterFluentChaining: options.vueRouterFluentChaining,
      routeMetaByComponent: options.routeMetaByComponent,
    });
    files.push({ filePath, content });
  }

  for (const targetClassName of stubTargets) {
    const filePath = generatedTsFilePathByComponent.get(targetClassName);
    if (!filePath) {
      continue;
    }

    const outputDir = path.dirname(filePath);
    const basePageImportSpecifier = stripExtension(toPosixRelativePath(outputDir, runtimeBasePagePath));
    const composed = getComposedStubBody(targetClassName, availableClassNames, depsByClassName, vueFilesPathMap, projectRoot);
    const childImports = (composed?.childClassNames ?? [])
      .map((childClassName) => {
        const childFilePath = generatedTsFilePathByComponent.get(childClassName);
        if (!childFilePath) {
          return null;
        }
        const importPath = stripExtension(toPosixRelativePath(outputDir, childFilePath));
        return `import { ${childClassName} } from "${importPath}";`;
      })
      .filter((line): line is string => !!line)
      .sort((a, b) => a.localeCompare(b));

    const body = composed?.lines ?? [
      "    constructor(page: PwPage) {",
      "        super(page);",
      "    }",
    ];

    const content = renderSplitStubPomContent({
      className: targetClassName,
      basePageImportSpecifier,
      childImports,
      bodyLines: body,
    });

    files.push({ filePath, content });
  }

  const runtimeFiles = buildRuntimeGeneratedFiles(base, basePageClassPath);
  const indexContent = [
    `${eslintSuppressionHeader}/**`,
    " * POM exports",
    AUTO_GENERATED_COMMENT,
    'export * from "./_pom-runtime/click-instrumentation";',
    'export * from "./_pom-runtime/class-generation/playwright-types";',
    'export * from "./_pom-runtime/class-generation/Pointer";',
    'export * from "./_pom-runtime/class-generation/BasePage";',
    "",
    ...Array.from(generatedTsFilePathByComponent.entries())
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([, filePath]) => `export * from "./${stripExtension(path.basename(filePath))}";`),
    "",
  ].join("\n");

  return [
    ...files,
    { filePath: path.join(base, "index.ts"), content: indexContent },
    ...runtimeFiles,
  ];
}

function escapeGitAttributesPattern(value: string): string {
  let output = "";
  for (let i = 0; i < value.length; i++) {
    const char = value[i];
    if (char === "\\") {
      output += "\\\\";
      continue;
    }
    if (char === " ") {
      output += "\\ ";
      continue;
    }
    if (i === 0 && (char === "#" || char === "!")) {
      output += `\\${char}`;
      continue;
    }
    output += char;
  }
  return output;
}

function pathUsesGeneratedHeuristic(filePath: string): boolean {
  const normalized = path.normalize(filePath);
  return normalized.split(path.sep).includes("__generated__");
}

function buildManagedGitAttributesBlock(entries: string[]): string {
  return [
    GENERATED_GITATTRIBUTES_BLOCK_START,
    "# GitHub Linguist: treat generated POM outputs as generated code by default.",
    ...entries,
    GENERATED_GITATTRIBUTES_BLOCK_END,
    "",
  ].join("\n");
}

function findLineEndOffset(content: string, offset: number): number {
  let cursor = offset;
  while (cursor < content.length && content[cursor] !== "\n") {
    cursor++;
  }
  if (cursor < content.length && content[cursor] === "\n") {
    cursor++;
  }
  return cursor;
}

function renderManagedGitAttributesContent(filePath: string, entries: string[]): string {
  const block = buildManagedGitAttributesBlock(entries);
  if (!fs.existsSync(filePath)) {
    return block;
  }

  const existingContent = fs.readFileSync(filePath, "utf8");
  const blockStart = existingContent.indexOf(GENERATED_GITATTRIBUTES_BLOCK_START);
  const blockEnd = existingContent.indexOf(GENERATED_GITATTRIBUTES_BLOCK_END);

  if (blockStart === -1 && blockEnd === -1) {
    if (!existingContent.length) {
      return block;
    }

    const separator = existingContent.endsWith("\n") ? "\n" : "\n\n";
    return `${existingContent}${separator}${block}`;
  }

  if (blockStart === -1 || blockEnd === -1 || blockEnd < blockStart) {
    throw new Error(`[vue-pom-generator] Found malformed managed .gitattributes block at ${filePath}.`);
  }

  const afterBlock = findLineEndOffset(existingContent, blockEnd);
  return `${existingContent.slice(0, blockStart)}${block}${existingContent.slice(afterBlock)}`;
}

function buildGeneratedGitAttributesFiles(generatedFilePaths: string[]): GeneratedFileOutput[] {
  const entriesByDir = new Map<string, Set<string>>();

  for (const generatedFilePath of generatedFilePaths) {
    const resolvedFilePath = path.resolve(generatedFilePath);
    if (path.basename(resolvedFilePath) === ".gitattributes") {
      continue;
    }

    if (pathUsesGeneratedHeuristic(resolvedFilePath)) {
      continue;
    }

    const dir = path.dirname(resolvedFilePath);
    const entry = `${escapeGitAttributesPattern(path.basename(resolvedFilePath))} linguist-generated`;
    const entries = entriesByDir.get(dir) ?? new Set<string>();
    entries.add(entry);
    entriesByDir.set(dir, entries);
  }

  return Array.from(entriesByDir.entries())
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([dir, entries]) => {
      const filePath = path.join(dir, ".gitattributes");
      const content = renderManagedGitAttributesContent(
        filePath,
        Array.from(entries).sort((a, b) => a.localeCompare(b)),
      );
      return { filePath, content };
    });
}

function toCSharpTestIdExpression(formattedDataTestId: string): string {
  // Convert our `${var}` placeholder format into C# interpolated-string `{var}`.
  const needsInterpolation = formattedDataTestId.includes("${");
  if (!needsInterpolation) {
    return JSON.stringify(formattedDataTestId);
  }

  const inner = formattedDataTestId.replace(/\$\{/g, "{");
  // Use verbatim JSON escaping for quotes/backslashes, then adapt to C# string literal.
  // JSON.stringify gives us a JS string literal with escapes, which is close enough for a C# normal string.
  const quoted = JSON.stringify(inner);
  return `$${quoted}`;
}

function toCSharpParam(paramTypeExpr: string): { type: string; defaultExpr?: string } {
  const trimmed = (paramTypeExpr ?? "").trim();

  // Handle default values: "boolean = true", "string = \"\"", "timeOut = 500".
  const eqIdx = trimmed.indexOf("=");
  const left = eqIdx >= 0 ? trimmed.slice(0, eqIdx).trim() : trimmed;
  const right = eqIdx >= 0 ? trimmed.slice(eqIdx + 1).trim() : undefined;

  // Collapse union types to their widest practical type.
  const typePart = left.includes("|") ? "string" : left;

  let type = "string";
  if (/(?:^|\s)boolean(?:\s|$)/.test(typePart))
    type = "bool";
  else if (/(?:^|\s)string(?:\s|$)/.test(typePart))
    type = "string";
  else if (/(?:^|\s)number(?:\s|$)/.test(typePart))
    type = "int";
  else if (/\d+/.test(typePart) && typePart === "")
    type = "int";
  else if (/\btimeOut\b/i.test(typePart))
    type = "int";

  let defaultExpr: string | undefined;
  if (right !== undefined) {
    if (type === "bool") {
      defaultExpr = right.includes("true") ? "true" : right.includes("false") ? "false" : undefined;
    }
    else if (type === "int") {
      const m = right.match(/\d+/);
      defaultExpr = m ? m[0] : undefined;
    }
    else {
      // string defaults, keep empty string if detected.
      if (right === "\"\"" || right === "\"\"" || right === "''") {
        defaultExpr = "\"\"";
      }
    }
  }

  return { type, defaultExpr };
}

function formatCSharpParams(params: Record<string, string> | undefined): { signature: string; argNames: string[] } {
  if (!params)
    return { signature: "", argNames: [] };

  const entries = Object.entries(params);
  if (!entries.length)
    return { signature: "", argNames: [] };

  const signatureParts: string[] = [];
  const argNames: string[] = [];

  for (const [name, typeExpr] of entries) {
    const { type, defaultExpr } = toCSharpParam(typeExpr);
    argNames.push(name);
    signatureParts.push(defaultExpr !== undefined ? `${type} ${name} = ${defaultExpr}` : `${type} ${name}`);
  }

  return { signature: signatureParts.join(", "), argNames };
}

function generateAggregatedCSharpFiles(
  componentHierarchyMap: Map<string, IComponentDependencies>,
  outDir: string,
  options: {
    projectRoot?: string;
    testIdAttribute?: string;
    csharp?: {
      namespace?: string;
    };
  } = {},
): GeneratedFileOutput[] {
  const outAbs = ensureDir(outDir);
  const namespace = options.csharp?.namespace ?? "Playwright.Generated";
  const testIdAttribute = (options.testIdAttribute || "data-testid").trim() || "data-testid";

  const entries = Array.from(componentHierarchyMap.entries()).sort((a, b) => a[0].localeCompare(b[0]));

  const header = [
    "// <auto-generated>",
    "// DO NOT MODIFY BY HAND",
    "//",
    "// This file is auto-generated by vue-pom-generator.",
    "// Changes should be made in the generator/template, not in the generated output.",
    "// </auto-generated>",
    "",
    "using System;",
    "using System.Threading.Tasks;",
    "using Microsoft.Playwright;",
    "",
    `namespace ${namespace};`,
    "",
    "public abstract partial class BasePage",
    "{",
    "    protected BasePage(IPage page) => Page = page;",
    "    protected IPage Page { get; }",
    `    protected ILocator LocatorByTestId(string testId) => Page.Locator($"[${testIdAttribute}=\\"{testId}\\"]");`,
    "    protected ILocator LocatorWithinTestIdByLabel(string rootTestId, string label, bool exact = true) => LocatorByTestId(rootTestId).GetByLabel(label, new() { Exact = exact });",
    "    protected async Task<ILocator> ResolveEditableLocatorAsync(ILocator locator)",
    "    {",
    "        var isEditable = await locator.EvaluateAsync<bool>(@\"el => {",
    "            if (!el || !(el instanceof HTMLElement)) return false;",
    "            const tagName = el.tagName.toLowerCase();",
    "            return tagName === 'input' || tagName === 'textarea' || tagName === 'select' || el.isContentEditable;",
    "        }\");",
    "        if (isEditable)",
    "        {",
    "            return locator;",
    "        }",
    "",
    "        var descendant = locator.Locator(\"input, textarea, select, [contenteditable=''], [contenteditable='true'], [contenteditable]:not([contenteditable='false'])\").First;",
    "        if (await descendant.CountAsync() > 0)",
    "        {",
    "            return descendant;",
    "        }",
    "",
    "        return locator;",
    "    }",
    "    protected async Task ClickWithinTestIdByLabelAsync(string rootTestId, string label, bool exact = true)",
    "    {",
    "        await LocatorWithinTestIdByLabel(rootTestId, label, exact).ClickAsync();",
    "    }",
    "",
    "    // Minimal vue-select helper mirroring the TS BasePage.selectVSelectByTestId behavior.",
    "    // Note: annotationText is currently a no-op in C# output (we don't render a cursor overlay).",
    "    protected async Task SelectVSelectByTestIdAsync(string testId, string value, int timeOut = 500)",
    "    {",
    "        var root = LocatorByTestId(testId);",
    "        var input = root.Locator(\"input\");",
    "",
    "        await input.ClickAsync(new LocatorClickOptions { Force = true });",
    "        await input.FillAsync(value);",
    "        await Page.WaitForTimeoutAsync(timeOut);",
    "",
    "        var option = root.Locator(\"ul.vs__dropdown-menu li[role='option']\").First;",
    "        if (await option.CountAsync() > 0)",
    "        {",
    "            await option.ClickAsync();",
    "        }",
    "    }",
    "}",
    "",
  ].join("\n");

  const chunks: string[] = [header];

  for (const [componentName, deps] of entries) {
    const className = toPascalCaseLocal(componentName);
    chunks.push(
      `public partial class ${className} : BasePage\n{\n    public ${className}(IPage page) : base(page) { }\n`,
    );

    // Primary specs
    const primaries = Array.from(deps.dataTestIdSet ?? [])
      .map(e => ({ pom: e.pom, target: e.targetPageObjectModelClass }))
      .filter((x): x is { pom: PomPrimarySpec; target: string | undefined } => !!x.pom)
      .sort((a, b) => a.pom.methodName.localeCompare(b.pom.methodName));

    for (const { pom, target } of primaries) {
      if (pom.emitPrimary === false)
        continue;

      const roleSuffix = (pom.nativeRole || "Element") === "vselect" ? "VSelect" : upperFirst(pom.nativeRole || "Element");
      const baseMethodName = upperFirst(pom.methodName);
      const baseGetterName = upperFirst(pom.getterNameOverride ?? pom.methodName);
      const locatorName = baseGetterName.endsWith(roleSuffix) ? baseGetterName : `${baseGetterName}${roleSuffix}`;
      const testIdExpr = toCSharpTestIdExpression(pom.formattedDataTestId);

      // Ensure all template variables referenced in formattedDataTestId (e.g. `${key}`)
      // appear in the C# method signature.  utils.ts may omit `key` for input/select
      // elements even when the test ID is dynamic, causing CS0103 compile errors.
      const templateVarMatches = [...pom.formattedDataTestId.matchAll(/\$\{(\w+)\}/g)];
      const templateVars = templateVarMatches.map(m => m[1]);
      const augmentedParams: Record<string, string> = { ...pom.params };
      for (const v of templateVars) {
        if (!Object.prototype.hasOwnProperty.call(augmentedParams, v)) {
          augmentedParams[v] = "string";
        }
      }
      // Place template vars first so they precede text/value/annotationText.
      const orderedParams: Record<string, string> = Object.fromEntries([
        ...templateVars.map(v => [v, augmentedParams[v]] as [string, string]),
        ...Object.entries(augmentedParams).filter(([k]) => !templateVars.includes(k)),
      ]);

      const { signature, argNames } = formatCSharpParams(orderedParams);
      const args = argNames.join(", ");

      const allTestIds = [pom.formattedDataTestId, ...(pom.alternateFormattedDataTestIds ?? [])]
        .filter((v, idx, arr) => v && arr.indexOf(v) === idx);

      if (pom.formattedDataTestId.includes("${")) {
        chunks.push(`    public ILocator ${locatorName}(${signature}) => LocatorByTestId(${testIdExpr});`);
      }
      else {
        chunks.push(`    public ILocator ${locatorName} => LocatorByTestId(${testIdExpr});`);
      }

      // Action method
      const actionPrefix = pom.nativeRole === "input"
        ? "Type"
        : (pom.nativeRole === "select" || pom.nativeRole === "vselect" || pom.nativeRole === "radio")
          ? "Select"
          : target
            ? "GoTo"
            : "Click";

      const actionName = `${actionPrefix}${baseMethodName}Async`;
      const sig = signature;

      if (target) {
        chunks.push(`    public async Task<${target}> ${actionName}(${sig})`);
        chunks.push("    {");
        if (pom.formattedDataTestId.includes("${") || allTestIds.length <= 1) {
          chunks.push(`        await ${locatorName}${pom.formattedDataTestId.includes("${") ? `(${args})` : ""}.ClickAsync();`);
          chunks.push(`        return new ${target}(Page);`);
        }
        else {
          chunks.push("        Exception? lastError = null;");
          chunks.push(`        foreach (var testId in new[] { ${allTestIds.map(toCSharpTestIdExpression).join(", ")} })`);
          chunks.push("        {");
          chunks.push("            try");
          chunks.push("            {");
          chunks.push("                var locator = LocatorByTestId(testId);");
          chunks.push("                if (await locator.CountAsync() > 0)");
          chunks.push("                {");
          chunks.push("                    await locator.ClickAsync();");
          chunks.push(`                    return new ${target}(Page);`);
          chunks.push("                }");
          chunks.push("            }");
          chunks.push("            catch (Exception e)");
          chunks.push("            {");
          chunks.push("                lastError = e;");
          chunks.push("            }");
          chunks.push("        }");
          chunks.push("        throw lastError ?? new System.Exception(\"[pom] Failed to navigate using any candidate test id.\");");
        }
        chunks.push("    }");
        chunks.push("");
        continue;
      }

      chunks.push(`    public async Task ${actionName}(${sig})`);
      chunks.push("    {");

      const callSuffix = pom.formattedDataTestId.includes("${") ? `(${args})` : "";

      const emitActionCall = (locatorAccess: string) => {
        if (pom.nativeRole === "input") {
          chunks.push(`        var editableLocator = await ResolveEditableLocatorAsync(${locatorAccess});`);
          chunks.push("        await editableLocator.FillAsync(text);");
        }
        else if (pom.nativeRole === "select") {
          chunks.push(`        await ${locatorAccess}.SelectOptionAsync(value);`);
        }
        else if (pom.nativeRole === "vselect") {
          // vselect requires custom selection mechanics.
          chunks.push(`        await SelectVSelectByTestIdAsync(${testIdExpr}, value, timeOut);`);
        }
        else {
          chunks.push(`        await ${locatorAccess}.ClickAsync();`);
        }
      };

      if (!pom.formattedDataTestId.includes("${") && allTestIds.length > 1) {
        chunks.push("        Exception? lastError = null;");
        chunks.push(`        foreach (var testId in new[] { ${allTestIds.map(toCSharpTestIdExpression).join(", ")} })`);
        chunks.push("        {");
        chunks.push("            try");
        chunks.push("            {");
        if (pom.nativeRole === "vselect") {
          chunks.push("                // vselect fallback: use the same selection routine for each candidate test id.");
          chunks.push("                var root = LocatorByTestId(testId);");
          chunks.push("                if (await root.CountAsync() > 0)");
          chunks.push("                {");
          chunks.push("                    await SelectVSelectByTestIdAsync(testId, value, timeOut);");
          chunks.push("                    return;");
          chunks.push("                }");
        }
        else {
          chunks.push("                var locator = LocatorByTestId(testId);");
          chunks.push("                if (await locator.CountAsync() > 0)");
          chunks.push("                {");
          if (pom.nativeRole === "input") {
            chunks.push("                    var editableLocator = await ResolveEditableLocatorAsync(locator);");
            chunks.push("                    await editableLocator.FillAsync(text);");
          }
          else if (pom.nativeRole === "select") {
            chunks.push("                    await locator.SelectOptionAsync(value);");
          }
          else {
            chunks.push("                    await locator.ClickAsync();");
          }
          chunks.push("                    return;");
          chunks.push("                }");
        }
        chunks.push("            }");
        chunks.push("            catch (Exception e)");
        chunks.push("            {");
        chunks.push("                lastError = e;");
        chunks.push("            }");
        chunks.push("        }");
        chunks.push("        throw lastError ?? new Exception(\"[pom] Failed to click any candidate test id.\");");
        chunks.push("    }");
        chunks.push("");
        continue;
      }

      emitActionCall(`${locatorName}${callSuffix}`);

      chunks.push("    }");
      chunks.push("");
    }

    // Extra click specs
    const extras = (deps.pomExtraMethods ?? []).slice().sort((a, b) => a.name.localeCompare(b.name));
    for (const extra of extras) {
      if (extra.kind !== "click")
        continue;
      const { signature } = formatCSharpParams(extra.params);

      const extraName = upperFirst(extra.name);

      chunks.push(`    public async Task ${extraName}Async(${signature})`);
      chunks.push("    {");
      if (extra.keyLiteral !== undefined) {
        chunks.push(`        var key = ${JSON.stringify(extra.keyLiteral)};`);
      }

      if (extra.selector.kind === "testId") {
        const needsTemplate = extra.selector.formattedDataTestId.includes("${");
        const testIdExpr = toCSharpTestIdExpression(extra.selector.formattedDataTestId);
        if (needsTemplate) {
          chunks.push(`        var testId = ${testIdExpr};`);
          chunks.push("        await LocatorByTestId(testId).ClickAsync();");
        }
        else {
          chunks.push(`        await LocatorByTestId(${testIdExpr}).ClickAsync();`);
        }
      }
      else {
        const rootNeedsTemplate = extra.selector.rootFormattedDataTestId.includes("${");
        const labelNeedsTemplate = extra.selector.formattedLabel.includes("${");
        const rootExpr = toCSharpTestIdExpression(extra.selector.rootFormattedDataTestId);
        const labelExpr = toCSharpTestIdExpression(extra.selector.formattedLabel);
        const exactArg = extra.selector.exact === false ? "false" : "true";

        if (rootNeedsTemplate) {
          chunks.push(`        var rootTestId = ${rootExpr};`);
        }
        if (labelNeedsTemplate) {
          chunks.push(`        var label = ${labelExpr};`);
        }

        const rootArg = rootNeedsTemplate ? "rootTestId" : rootExpr;
        const labelArg = labelNeedsTemplate ? "label" : labelExpr;
        chunks.push(`        await ClickWithinTestIdByLabelAsync(${rootArg}, ${labelArg}, ${exactArg});`);
      }
      chunks.push("    }");
      chunks.push("");
    }

    chunks.push("}");
    chunks.push("");
  }

  const outputFile = path.join(outAbs, "page-object-models.g.cs");
  return [{ filePath: outputFile, content: chunks.join("\n") }];
}

function maybeGenerateFixtureRegistry(
  componentHierarchyMap: Map<string, IComponentDependencies>,
  options: {
    generateFixtures: GenerateFilesOptions["generateFixtures"];
    pomOutDir: string;
    projectRoot?: string;
    customPomDir?: string;
  },
): GeneratedFileOutput | null {
  const { generateFixtures, pomOutDir } = options;
  if (!generateFixtures)
    return null;

  // generateFixtures accepts:
  // - true: enable fixtures with defaults
  // - "path": enable fixtures and write them under this directory OR to this file if it ends with .ts
  // - { outDir }: enable fixtures and override output directory
  const defaultFixtureOutDirRel = pomOutDir;
  const fixtureOutRel = typeof generateFixtures === "string"
    ? generateFixtures
    : (typeof generateFixtures === "object" && generateFixtures?.outDir
      ? generateFixtures.outDir
      : defaultFixtureOutDirRel);

  const looksLikeFilePath = fixtureOutRel.endsWith(".ts") || fixtureOutRel.endsWith(".tsx") || fixtureOutRel.endsWith(".mts") || fixtureOutRel.endsWith(".cts");
  const fixtureOutDirRel = looksLikeFilePath ? path.dirname(fixtureOutRel) : fixtureOutRel;
  const fixtureFileName = looksLikeFilePath ? path.basename(fixtureOutRel) : "fixtures.g.ts";

  const root = options.projectRoot ?? process.cwd();
  const fixtureOutDirAbs = path.isAbsolute(fixtureOutDirRel)
    ? fixtureOutDirRel
    : path.resolve(root, fixtureOutDirRel);

  const customPomDirRel = options.customPomDir ?? "tests/playwright/pom/custom";
  const customPomDirAbs = path.isAbsolute(customPomDirRel)
    ? customPomDirRel
    : path.resolve(root, customPomDirRel);
  const overridePomDirAbs = path.resolve(path.dirname(customPomDirAbs), "overrides");

  // Resolve the directory that contains the POM barrel export (e.g. <root>/pom).
  const pomDirAbs = path.isAbsolute(pomOutDir) ? pomOutDir : path.resolve(root, pomOutDir);

  const pomImport = toPosixRelativePath(fixtureOutDirAbs, pomDirAbs);

  const viewClassNames = Array.from(componentHierarchyMap.entries())
    .filter(([, deps]) => !!deps.isView)
    .map(([name]) => name)
    .sort((a, b) => a.localeCompare(b));

  const reservedPlaywrightFixtureNames = new Set([
    // Built-in Playwright fixtures
    "page",
    "context",
    "browser",
    "browserName",
    "request",
    // Our own fixtureOptions
    "animation",
  ]);

  const viewFixtureNames = new Set(viewClassNames.map(name => lowerFirst(name)));

  const componentClassNames = Array.from(componentHierarchyMap.entries())
    .filter(([, deps]) => !deps.isView)
    .map(([name]) => name)
    .filter((name) => {
      const fixtureName = lowerFirst(name);
      if (reservedPlaywrightFixtureNames.has(fixtureName))
        return false;
      if (viewFixtureNames.has(fixtureName))
        return false;
      return true;
    })
    .sort((a, b) => a.localeCompare(b));

  const fixtureClassNames = [...viewClassNames, ...componentClassNames];
  const overrideCtorEntries = fixtureClassNames
    .map((name) => {
      const overrideFilePath = path.join(overridePomDirAbs, `${name}.ts`);
      if (!fs.existsSync(overrideFilePath))
        return null;

      return {
        className: name,
        localIdentifier: `${name}Override`,
        importSpecifier: stripExtension(toPosixRelativePath(fixtureOutDirAbs, overrideFilePath)),
      };
    })
    .filter((entry): entry is { className: string; localIdentifier: string; importSpecifier: string } => !!entry);
  const overrideCtorByClassName = new Map(overrideCtorEntries.map(entry => [entry.className, entry.localIdentifier]));
  const overrideImports = overrideCtorEntries.length
    ? `${overrideCtorEntries
        .map(entry => `import { ${entry.className} as ${entry.localIdentifier} } from "${entry.importSpecifier}";`)
        .join("\n")}\n\n`
    : "";

  const fixtureCtorExpression = (name: string) => overrideCtorByClassName.get(name) ?? `Pom.${name}`;

  const header = `${eslintSuppressionHeader}/**\n`
    + ` * DO NOT MODIFY BY HAND\n`
    + ` *\n`
    + ` * This file is auto-generated by vue-pom-generator.\n`
    + ` * Changes should be made in the generator/template, not in the generated output.\n`
    + ` */\n\n`;

  // Concrete, strongly-typed fixtures for Playwright tests.
  //   test("...", async ({ preferencesPage }) => { ... })
  //
  // View POMs implement goTo() directly, so fixtures can be strongly typed without
  // casting/augmenting at runtime.
  const fixturesTypeEntries = viewClassNames
    .map(name => `  ${lowerFirst(name)}: ${fixtureCtorExpression(name)},`)
    .join("\n");

  const componentFixturesTypeEntries = componentClassNames
    .map(name => `  ${lowerFirst(name)}: ${fixtureCtorExpression(name)},`)
    .join("\n");

  const pomFactoryType = `export type PomConstructor<T> = new (page: PwPage) => T;\n\n`
    + `export interface PomFactory {\n`
    + `  create<T>(ctor: PomConstructor<T>): T;\n`
    + `}\n\n`;

  // NOTE: We intentionally do not generate "openXPage" helpers.
  // Each view POM provides goTo(), and tests call it explicitly.

  // Openers removed.

  const fixturesContent = `${header
  }/** Generated Playwright fixtures (typed page objects). */\n\n`
  + `import { expect, test as base } from "@playwright/test";\n`
  + `import type { Page as PwPage } from "@playwright/test";\n`
  + `import * as Pom from "${pomImport}";\n`
  + `${overrideImports}`
  + `export interface PlaywrightOptions {\n`
  + `  animation: Pom.PlaywrightAnimationOptions;\n`
  + `}\n\n`
  + `${pomFactoryType}`
  + `type PomSetupFixture = { pomSetup: void };\n`
  + `type PomFactoryFixture = { pomFactory: PomFactory };\n\n`
            + `const pageCtors = {\n${fixturesTypeEntries}\n} as const;\n`
                + `const componentCtors = {\n${componentFixturesTypeEntries}\n} as const;\n\n`
                + `export type GeneratedPageFixtures = { [K in keyof typeof pageCtors]: InstanceType<(typeof pageCtors)[K]> };\n`
                + `export type GeneratedComponentFixtures = { [K in keyof typeof componentCtors]: InstanceType<(typeof componentCtors)[K]> };\n\n`
                + `const makePomFixture = <T>(Ctor: PomConstructor<T>) => async ({ page }: { page: PwPage }, use: (t: T) => Promise<void>) => {\n`
                + `  await use(new Ctor(page));\n`
                + `};\n\n`
                + `const createPomFixtures = <TMap extends Record<string, PomConstructor<any>>>(ctors: TMap) => {\n`
                + `  const out: Record<string, any> = {};\n`
                + `  for (const [key, Ctor] of Object.entries(ctors)) {\n`
                + `    out[key] = makePomFixture(Ctor as PomConstructor<any>);\n`
                + `  }\n`
                + `  return out as any;\n`
                + `};\n\n`
                + `const test = base.extend<PlaywrightOptions & PomSetupFixture & PomFactoryFixture & GeneratedPageFixtures & GeneratedComponentFixtures>({\n`
                + `  animation: [{\n`
                + `    pointer: { durationMilliseconds: 250, transitionStyle: "ease-in-out", clickDelayMilliseconds: 0 },\n`
                + `    keyboard: { typeDelayMilliseconds: 100 },\n`
                + `  }, { option: true }],\n`
                + `  pomSetup: [async ({ animation }, use) => {\n`
                + `    Pom.setPlaywrightAnimationOptions(animation);\n`
                + `    await use();\n`
                + `  }, { auto: true }],\n`
                + `  pomFactory: async ({ page }, use) => {\n`
                + `    await use({\n`
                + `      create: <T>(ctor: PomConstructor<T>) => new ctor(page),\n`
                + `    });\n`
                + `  },\n`
                + `  ...createPomFixtures(pageCtors),\n`
                + `  ...createPomFixtures(componentCtors),\n`
                + `});\n\n`
                + `export { test, expect };\n`;

  return {
    filePath: path.resolve(fixtureOutDirAbs, fixtureFileName),
    content: fixturesContent,
  };

  // No pomFixture is generated; goToSelf is emitted directly on each view POM.
}

function generateViewObjectModelContent(
  componentName: string,
  dependencies: IComponentDependencies,
  componentHierarchyMap: Map<string, IComponentDependencies>,
  vueFilesPathMap: Map<string, string>,
  basePageClassPath: string,
  options: GenerateContentOptions = {},
) {
  const { isView, childrenComponentSet, usedComponentSet, filePath } = dependencies;

  const {
    outputDir = path.dirname(filePath),
    outputStructure = "split",
    customPomAttachments = [],
    testIdAttribute,
  } = options;
  const aggregated = outputStructure === "aggregated";

  const hasChildComponent = (needle: string) => {
    const haystack = usedComponentSet?.size ? usedComponentSet : childrenComponentSet;
    for (const child of haystack) {
      if (child === needle)
        return true;
      if (child === `${needle}.vue`)
        return true;
      if (child.endsWith(".vue") && child.slice(0, -4) === needle)
        return true;
    }
    return false;
  };

  const customPomClassIdentifierMap = options.customPomClassIdentifierMap ?? {};
  const customPomAvailableClassIdentifiers = options.customPomAvailableClassIdentifiers ?? new Set<string>();
  const customPomImportSpecifiersByClass = options.customPomImportSpecifiersByClass ?? {};
  const customPomMethodSignaturesByClass = options.customPomMethodSignaturesByClass ?? new Map<string, CustomPomMethodSignatureMap>();

  const attachmentsForThisClass = customPomAttachments
    .filter((a) => {
      if (!Object.prototype.hasOwnProperty.call(customPomClassIdentifierMap, a.className))
        return false;

      const scope = a.attachTo ?? "views";
      const scopeMatchesBoth = scope === "both" || scope === "pagesAndComponents";
      const scopeOk = isView
        ? (scope === "views" || scopeMatchesBoth)
        : (scope === "components" || scopeMatchesBoth);
      if (!scopeOk)
        return false;
      return a.attachWhenUsesComponents.some(c => hasChildComponent(c));
    })
    .map(a => ({
      className: customPomClassIdentifierMap[a.className]!,
      propertyName: a.propertyName,
      flatten: a.flatten ?? false,
      methodSignatures: a.flatten
        ? (customPomMethodSignaturesByClass.get(a.className) ?? new Map<string, CustomPomMethodSignature>())
        : new Map<string, CustomPomMethodSignature>(),
    }));

  const widgetInstances = isView
    ? getWidgetInstancesForView(componentName, dependencies.dataTestIdSet, customPomAvailableClassIdentifiers)
    : [];

  // For views, `childrenComponentSet` only includes component tags on which we applied a data-testid.
  // Thin wrapper views (e.g. NewTenantPage) may have *no* generated test ids but still contain
  // important child component POMs (forms, grids, etc). In those cases, we use `usedComponentSet`
  // to discover and instantiate child component POMs.
  const componentRefsForInstances = isView
    ? (usedComponentSet?.size ? usedComponentSet : childrenComponentSet)
    : childrenComponentSet;

  let content: string = "";

  const sourceRel = toPosixRelativePath(outputDir, filePath);
  const kind = isView ? "Page" : "Component";
  const doc = `/** ${kind} POM: ${componentName} (source: ${sourceRel}) */\n`;

  // In aggregated mode, imports are hoisted once at the top of the file.
  if (!aggregated) {
    content = `${eslintSuppressionHeader}${doc}`;

    // We only need PwPage when we emit a constructor (views always do; components only do
    // when they have custom attachments like Grid).
    if (isView || attachmentsForThisClass.length > 0) {
      content += "import type { Page as PwPage } from \"@playwright/test\";\n";
    }

    const projectRoot = options.projectRoot ?? process.cwd();
    const fromAbs = path.isAbsolute(outputDir) ? outputDir : path.resolve(projectRoot, outputDir);
    const toAbs = basePageClassPath
      ? (path.isAbsolute(basePageClassPath) ? basePageClassPath : path.resolve(projectRoot, basePageClassPath))
      : "";
    const basePageImport = path.relative(fromAbs, toAbs).replace(/\\/g, "/");
    // stripExtension uses node:path formatting (platform-specific). Re-normalize to POSIX
    // so the import specifier is valid on Windows.
    const basePageImportNoExt = stripExtension(basePageImport).replace(/\\/g, "/");
    const basePageImportSpecifier = basePageImportNoExt.startsWith(".") ? basePageImportNoExt : `./${basePageImportNoExt}`;
    content += `import { BasePage, Fluent } from '${basePageImportSpecifier}';\n\n`;

    const generatedImportLines: string[] = [];
    const importedGeneratedClasses = new Set<string>();
    const generatedTsFilePathByComponent = options.generatedTsFilePathByComponent;

    const addGeneratedImport = (className: string) => {
      if (!generatedTsFilePathByComponent || importedGeneratedClasses.has(className) || className === componentName) {
        return;
      }
      const generatedFilePath = generatedTsFilePathByComponent.get(className);
      if (!generatedFilePath) {
        return;
      }

      const importPath = stripExtension(toPosixRelativePath(fromAbs, generatedFilePath));
      generatedImportLines.push(`import { ${className} } from '${importPath}';`);
      importedGeneratedClasses.add(className);
    };

    const customImportLines = Array.from(
      new Set([
        ...attachmentsForThisClass.map(attachment => attachment.className),
        ...widgetInstances.map(widget => widget.className),
      ]),
    )
      .map((localIdentifier) => {
        const specifier = Object.values(customPomImportSpecifiersByClass)
          .find(spec => spec.localIdentifier === localIdentifier);
        if (!specifier) {
          return null;
        }

        const importPath = stripExtension(toPosixRelativePath(fromAbs, specifier.absolutePath));
        if (specifier.localIdentifier !== specifier.exportName) {
          return `import { ${specifier.exportName} as ${specifier.localIdentifier} } from "${importPath}";`;
        }
        return `import { ${specifier.exportName} } from "${importPath}";`;
      })
      .filter((line): line is string => !!line)
      .sort((a, b) => a.localeCompare(b));

    for (const child of componentRefsForInstances) {
      const childName = child.endsWith(".vue") ? child.slice(0, -4) : child;
      const childDeps = componentHierarchyMap.get(child) ?? componentHierarchyMap.get(childName);
      if (childDeps?.dataTestIdSet.size) {
        addGeneratedImport(childName);
      }
    }

    const targetClassNames = Array.from(
      new Set(
        Array.from(dependencies.dataTestIdSet ?? [])
          .map(entry => entry.targetPageObjectModelClass)
          .filter((target): target is string => typeof target === "string" && target.length > 0),
      ),
    ).sort((a, b) => a.localeCompare(b));

    for (const targetClassName of targetClassNames) {
      addGeneratedImport(targetClassName);
    }

    if (customImportLines.length > 0) {
      content += `${customImportLines.join("\n")}\n`;
    }
    if (generatedImportLines.length > 0) {
      content += `${generatedImportLines.join("\n")}\n`;
    }
    if (customImportLines.length > 0 || generatedImportLines.length > 0) {
      content += "\n";
    }
  }
  else {
    // Keep per-class doc comment, but avoid repeating eslint suppression / imports.
    content = doc;
  }

  // Convert raw component name (may contain hyphens/dots, e.g. "error-test", "FirmsGrid.client")
  // to a valid PascalCase TypeScript identifier for the class declaration.
  const className = toPascalCaseLocal(componentName);
  content += `\nexport class ${className} extends BasePage {\n`;
  const childInstancePropertyNames = Array.from(componentRefsForInstances)
    .filter(child => componentHierarchyMap.has(child) && componentHierarchyMap.get(child)?.dataTestIdSet.size)
    .map(child => child.split(".vue")[0]);
  const blockedViewPassthroughMethodNames = new Set(
    attachmentsForThisClass
      .filter(a => a.flatten)
      .flatMap(a => Array.from(a.methodSignatures.keys())),
  );
  const reservedAttachmentPassthroughNames = new Set<string>([
    ...attachmentsForThisClass.map(a => a.propertyName),
    ...widgetInstances.map(w => w.propertyName),
    ...childInstancePropertyNames,
  ]);

  // Only views get child component instance fields by default.
  // Components will only get a constructor/fields when they have explicit custom attachments
  // (e.g. wrapper components around a third-party data grid should get a `grid: Grid`).
  if (isView && (componentRefsForInstances.size > 0 || attachmentsForThisClass.length > 0 || widgetInstances.length > 0)) {
    content += getComponentInstances(componentRefsForInstances, componentHierarchyMap, attachmentsForThisClass, widgetInstances);
    content += getConstructor(componentRefsForInstances, componentHierarchyMap, attachmentsForThisClass, widgetInstances, { testIdAttribute });
  }
  if (!isView && attachmentsForThisClass.length > 0) {
    content += getComponentInstances(new Set(), componentHierarchyMap, attachmentsForThisClass);
    content += getConstructor(new Set(), componentHierarchyMap, attachmentsForThisClass, [], { testIdAttribute });
  }
  content += getAttachmentPassthroughMethods(componentName, dependencies, attachmentsForThisClass, reservedAttachmentPassthroughNames);

  // Ergonomics: when a view is primarily composed of a single component POM (e.g. a form),
  // allow calling that component's methods directly on the page class.
  //
  // Example:
  //   await tenantListPage.goToNewTenant().typeTenantName(...).clickCreateTenant();
  //
  // Rules:
  // - Only for views (not components) to avoid polluting component surfaces.
  // - Only generate pass-throughs when the method is unambiguous across child components.
  // - Never generate a pass-through that would collide with an existing method on the view.
  // Only generate view passthrough methods when the view is essentially a thin wrapper
  // around a single child component POM. This prevents "layout" components (Page, PageHeader,
  // etc.) from injecting lots of noisy passthrough APIs into every view.
  if (isView && componentRefsForInstances.size === 1) {
    content += getViewPassthroughMethods(componentName, dependencies, componentRefsForInstances, componentHierarchyMap, blockedViewPassthroughMethodNames);
  }

  if (isView && options.vueRouterFluentChaining) {
    const routeMeta = options.routeMetaByComponent?.[componentName] ?? null;
    content += generateRouteProperty(routeMeta);
    // Pass className (PascalCase) so the generated route self-reference is a valid identifier.
    content += generateGoToSelfMethod(className);
  }

  content += generateMethodsContentForDependencies(dependencies);

  content += "}\n";
  return content;
}

function getViewPassthroughMethods(
  viewName: string,
  viewDependencies: IComponentDependencies,
  childrenComponentSet: Set<string>,
  componentHierarchyMap: Map<string, IComponentDependencies>,
  blockedMethodNames: Set<string> = new Set(),
) {
  const existingOnView = viewDependencies.generatedMethods ?? new Map<string, { params: string; argNames: string[] } | null>();

  // methodName -> candidates
  const methodToChildren = new Map<string, Array<{ childProp: string; params: string; argNames: string[] }>>();

  for (const child of childrenComponentSet) {
    const childDeps = componentHierarchyMap.get(child);
    if (!childDeps || !childDeps.dataTestIdSet?.size)
      continue;

    const methods = childDeps.generatedMethods;
    if (!methods)
      continue;

    // Property name matches how we emit instance fields (strip .vue if present).
    const childProp = child.endsWith(".vue") ? child.slice(0, -4) : child;

    for (const [name, sig] of methods.entries()) {
      if (!sig)
        continue; // ambiguous on the child itself

      // If the view already has this method name, never generate a pass-through.
      if (existingOnView.has(name) || blockedMethodNames.has(name))
        continue;

      const list = methodToChildren.get(name) ?? [];
      list.push({ childProp, params: sig.params, argNames: sig.argNames });
      methodToChildren.set(name, list);
    }
  }

  const sorted = Array.from(methodToChildren.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  const lines: string[] = [];

  for (const [methodName, candidates] of sorted) {
    // Only generate when exactly one child can satisfy the call.
    if (candidates.length !== 1)
      continue;

    const { childProp, params, argNames } = candidates[0];
    const callArgs = argNames.join(", ");

    lines.push(
      "",
      `    async ${methodName}(${params}) {`,
      `        return await this.${childProp}.${methodName}(${callArgs});`,
      "    }",
    );
  }

  if (!lines.length) {
    return "";
  }

  return [
    "",
    `    // Passthrough methods composed from child component POMs of ${viewName}.`,
    ...lines,
    "",
  ].join("\n");
}

function getAttachmentPassthroughMethods(
  ownerName: string,
  ownerDependencies: IComponentDependencies,
  attachmentsForThisClass: ResolvedCustomPomAttachment[],
  reservedMemberNames: Set<string>,
) {
  if (!attachmentsForThisClass.some(a => a.flatten && a.methodSignatures.size > 0)) {
    return "";
  }

  const existingOnClass = ownerDependencies.generatedMethods ?? new Map<string, { params: string; argNames: string[] } | null>();
  const methodToAttachments = new Map<string, Array<{ propertyName: string; params: string; argNames: string[] }>>();

  for (const attachment of attachmentsForThisClass) {
    if (!attachment.flatten) {
      continue;
    }

    for (const [methodName, signature] of attachment.methodSignatures.entries()) {
      if (methodName === "constructor" || existingOnClass.has(methodName) || reservedMemberNames.has(methodName)) {
        continue;
      }

      const list = methodToAttachments.get(methodName) ?? [];
      list.push({
        propertyName: attachment.propertyName,
        params: signature.params,
        argNames: signature.argNames,
      });
      methodToAttachments.set(methodName, list);
    }
  }

  const sorted = Array.from(methodToAttachments.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  const lines: string[] = [];

  for (const [methodName, candidates] of sorted) {
    if (candidates.length !== 1) {
      continue;
    }

    const { propertyName, params, argNames } = candidates[0];
    const callArgs = argNames.join(", ");
    const invocation = callArgs
      ? `this.${propertyName}.${methodName}(${callArgs})`
      : `this.${propertyName}.${methodName}()`;

    lines.push(
      "",
      `    ${methodName}(${params}) {`,
      `        return ${invocation};`,
      "    }",
    );
  }

  if (!lines.length) {
    return "";
  }

  return [
    "",
    `    // Passthrough methods composed from custom helper attachments of ${ownerName}.`,
    ...lines,
    "",
  ].join("\n");
}

function sliceNodeSource(source: string, node: { start?: number | null; end?: number | null }): string | null {
  if (node.start == null || node.end == null) {
    return null;
  }

  const snippet = source.slice(node.start, node.end).trim();
  return snippet.length ? snippet : null;
}

function getCustomPomCallArgumentName(param: ClassMethod["params"][number]): string | null {
  if (param.type === "Identifier") {
    return param.name;
  }

  if (param.type === "AssignmentPattern") {
    return param.left.type === "Identifier" ? param.left.name : null;
  }

  if (param.type === "RestElement") {
    return param.argument.type === "Identifier" ? `...${param.argument.name}` : null;
  }

  return null;
}

function extractCustomPomMethodSignatures(source: string, exportName: string): CustomPomMethodSignatureMap {
  const signatures: CustomPomMethodSignatureMap = new Map();

  let ast: ReturnType<typeof parse>;
  try {
    ast = parse(source, {
      sourceType: "module",
      plugins: ["typescript", "jsx"],
    });
  }
  catch {
    return signatures;
  }

  for (const statement of ast.program.body) {
    if (statement.type !== "ExportNamedDeclaration" || !statement.declaration || statement.declaration.type !== "ClassDeclaration") {
      continue;
    }

    const declaration = statement.declaration;
    if (declaration.id?.name !== exportName) {
      continue;
    }

    for (const member of declaration.body.body) {
      if (member.type !== "ClassMethod" || member.kind !== "method" || member.static || member.computed) {
        continue;
      }

      if (member.accessibility === "private" || member.accessibility === "protected") {
        continue;
      }

      if (member.key.type !== "Identifier") {
        continue;
      }

      const params: string[] = [];
      const argNames: string[] = [];
      let supported = true;

      member.params.forEach((param) => {
        if (!supported) {
          return;
        }

        const paramSource = sliceNodeSource(source, param);
        const argName = getCustomPomCallArgumentName(param);
        if (!paramSource || !argName) {
          supported = false;
          return;
        }

        params.push(paramSource);
        argNames.push(argName);
      });

      if (!supported) {
        continue;
      }

      signatures.set(member.key.name, {
        params: params.join(", "),
        argNames,
      });
    }
  }

  return signatures;
}

function ensureDir(dir: string) {
  const normalized = dir.replace(/\\/g, "/");
  if (!fs.existsSync(normalized)) {
    fs.mkdirSync(normalized, { recursive: true });
  }
  return normalized;
}

function resolvePluginAsset(relative: string): string {
  try {
    return fileURLToPath(new URL(relative, import.meta.url));
  }
  catch {
    return path.resolve(__dirname, relative);
  }
}

function readTextAsset(absPath: string, description: string): string {
  try {
    return fs.readFileSync(absPath, "utf8");
  }
  catch {
    throw new VuePomGeneratorError(`Failed to read ${description} at ${absPath}`);
  }
}

let splitStubPomTemplate: string | undefined;

function replaceTemplateToken(content: string, token: string, value: string): string {
  return content.split(token).join(value);
}

function getSplitStubPomTemplate(): string {
  if (splitStubPomTemplate) {
    return splitStubPomTemplate;
  }

  splitStubPomTemplate = readTextAsset(
    resolvePluginAsset("../class-generation/SplitStubPage.template"),
    "SplitStubPage.template",
  );
  return splitStubPomTemplate;
}

function renderSplitStubPomContent(options: {
  className: string;
  basePageImportSpecifier: string;
  childImports: string[];
  bodyLines: string[];
}): string {
  let content = getSplitStubPomTemplate();
  content = replaceTemplateToken(content, "__CLASS_NAME__", options.className);
  content = replaceTemplateToken(content, "__AUTO_GENERATED_COMMENT__", AUTO_GENERATED_COMMENT);
  content = replaceTemplateToken(content, "__BASE_PAGE_IMPORT__", options.basePageImportSpecifier);
  content = replaceTemplateToken(content, "__CHILD_IMPORTS__", options.childImports.join("\n"));
  content = replaceTemplateToken(content, "__CLASS_BODY__", options.bodyLines.join("\n"));
  return content;
}

interface RuntimeGeneratedAssetSpec {
  absolutePath: string;
  description: string;
  outputPath: string;
}

function getRuntimeGeneratedAssetSpecs(baseDir: string, basePageClassPath: string): RuntimeGeneratedAssetSpec[] {
  const runtimeDirAbs = path.join(baseDir, "_pom-runtime");
  const runtimeClassGenAbs = path.join(runtimeDirAbs, "class-generation");
  const runtimeClassGenSourceDir = resolvePluginAsset("../class-generation");
  const runtimeClassGenFiles = fs.readdirSync(runtimeClassGenSourceDir)
    .filter(file => file.endsWith(".ts"))
    .filter(file => file !== "BasePage.ts" && file !== "index.ts")
    .sort((left, right) => left.localeCompare(right));

  return [
    {
      absolutePath: resolvePluginAsset("../click-instrumentation.ts"),
      description: "click-instrumentation.ts",
      outputPath: path.join(runtimeDirAbs, "click-instrumentation.ts"),
    },
    ...runtimeClassGenFiles.map(file => ({
      absolutePath: path.join(runtimeClassGenSourceDir, file),
      description: file,
      outputPath: path.join(runtimeClassGenAbs, file),
    })),
    {
      absolutePath: basePageClassPath,
      description: "BasePage.ts",
      outputPath: path.join(runtimeClassGenAbs, "BasePage.ts"),
    },
  ];
}

function buildRuntimeGeneratedFiles(baseDir: string, basePageClassPath: string): GeneratedFileOutput[] {
  return getRuntimeGeneratedAssetSpecs(baseDir, basePageClassPath).map(spec => ({
    filePath: spec.outputPath,
    content: readTextAsset(spec.absolutePath, spec.description),
  }));
}

function resolveCustomPomImportResolution(
  generatedClassNames: Set<string>,
  projectRoot: string,
  options: {
    customPomDir?: GenerateFilesOptions["customPomDir"];
    customPomImportAliases?: GenerateFilesOptions["customPomImportAliases"];
    customPomImportNameCollisionBehavior?: GenerateFilesOptions["customPomImportNameCollisionBehavior"];
  } = {},
): CustomPomImportResolution {
  const importAliases: Record<string, string> = {
    Toggle: "ToggleWidget",
    Checkbox: "CheckboxWidget",
    ...(options.customPomImportAliases),
  };
  const importCollisionBehavior = options.customPomImportNameCollisionBehavior ?? "error";

  const reservedIdentifiers = new Set<string>([
    "PwLocator",
    "PwPage",
    "BasePage",
    "Fluent",
    ...generatedClassNames,
  ]);
  const usedImportIdentifiers = new Set<string>();
  const classIdentifierMap: Record<string, string> = {};
  const methodSignaturesByClass = new Map<string, CustomPomMethodSignatureMap>();
  const importSpecifiersByClass: Record<string, ResolvedCustomPomImportSpecifier> = {};

  const ensureUniqueIdentifier = (base: string) => {
    let candidate = base;
    let i = 2;
    while (reservedIdentifiers.has(candidate) || usedImportIdentifiers.has(candidate)) {
      candidate = `${base}${i}`;
      i++;
    }
    usedImportIdentifiers.add(candidate);
    return candidate;
  };

  const customDirRelOrAbs = options.customPomDir ?? "tests/playwright/pom/custom";
  const customDirAbs = path.isAbsolute(customDirRelOrAbs)
    ? customDirRelOrAbs
    : path.resolve(projectRoot, customDirRelOrAbs);

  if (!fs.existsSync(customDirAbs)) {
    return {
      classIdentifierMap,
      methodSignaturesByClass,
      availableClassIdentifiers: new Set<string>(),
      importSpecifiersByClass,
    };
  }

  const files = fs.readdirSync(customDirAbs)
    .filter(f => f.endsWith(".ts"))
    .sort((a, b) => a.localeCompare(b));

  for (const file of files) {
    const exportName = file.replace(/\.ts$/i, "");
    const requested = importAliases[exportName] ?? exportName;
    const collidesWithGeneratedClass = generatedClassNames.has(requested);
    const explicitAliasProvided = Object.prototype.hasOwnProperty.call(importAliases, exportName);

    if (collidesWithGeneratedClass && importCollisionBehavior === "error") {
      throw createCustomPomImportCollisionError(exportName, requested);
    }

    let localIdentifier = requested;
    if (collidesWithGeneratedClass && importCollisionBehavior === "alias") {
      const aliasBase = explicitAliasProvided ? requested : `${exportName}Custom`;
      localIdentifier = ensureUniqueIdentifier(aliasBase);
    }
    else {
      localIdentifier = ensureUniqueIdentifier(requested);
    }

    const customFileAbs = path.join(customDirAbs, file);
    classIdentifierMap[exportName] = localIdentifier;
    importSpecifiersByClass[exportName] = {
      exportName,
      localIdentifier,
      absolutePath: customFileAbs,
    };

    const customPomMethodSignatures = extractCustomPomMethodSignatures(fs.readFileSync(customFileAbs, "utf8"), exportName);
    if (customPomMethodSignatures.size > 0) {
      methodSignaturesByClass.set(exportName, customPomMethodSignatures);
    }
  }

  return {
    classIdentifierMap,
    methodSignaturesByClass,
    availableClassIdentifiers: new Set(Object.values(classIdentifierMap)),
    importSpecifiersByClass,
  };
}

function getComposedStubBody(
  targetClassName: string,
  availableClassNames: Set<string>,
  depsByClassName: Map<string, IComponentDependencies>,
  vueFilesPathMap: Map<string, string>,
  projectRoot: string,
) {
  const filePath = resolveVueSourcePath(targetClassName, vueFilesPathMap, projectRoot);
  if (!filePath)
    return undefined;

  let source = "";
  try {
    source = fs.readFileSync(filePath, "utf8");
  }
  catch {
    return undefined;
  }

  const tags = getPascalCaseComponentTagsFromVueSource(source);
  const childClassNames = Array.from(
    new Set(
      tags
        .filter(name => availableClassNames.has(name))
        .filter(name => name !== targetClassName),
    ),
  ).sort((a, b) => a.localeCompare(b));

  if (!childClassNames.length)
    return undefined;

  const methodToChildren = new Map<string, Array<{ child: string; params: string; argNames: string[] }>>();
  for (const child of childClassNames) {
    const childDeps = depsByClassName.get(child);
    const methods = childDeps?.generatedMethods;
    if (!methods)
      continue;

    for (const [name, sig] of methods.entries()) {
      if (!sig)
        continue;
      const list = methodToChildren.get(name) ?? [];
      list.push({ child, params: sig.params, argNames: sig.argNames });
      methodToChildren.set(name, list);
    }
  }

  const passthroughLines: string[] = [];
  for (const [methodName, candidatesForMethod] of methodToChildren.entries()) {
    if (candidatesForMethod.length !== 1 || methodName === "constructor")
      continue;

    const { child, params, argNames } = candidatesForMethod[0];
    const callArgs = argNames.join(", ");

    passthroughLines.push(
      "",
      `    async ${methodName}(${params}) {`,
      `        return await this.${child}.${methodName}(${callArgs});`,
      "    }",
    );
  }

  return {
    childClassNames,
    lines: [
      ...childClassNames.map(c => `    ${c}: ${c};`),
      "",
      "    constructor(page: PwPage) {",
      "        super(page);",
      ...childClassNames.map(c => `        this.${c} = new ${c}(page);`),
      "    }",
      ...passthroughLines,
    ],
  };
}

async function generateAggregatedFiles(
  componentHierarchyMap: Map<string, IComponentDependencies>,
  vueFilesPathMap: Map<string, string>,
  basePageClassPath: string,
  outDir: string,
  options: {
    customPomAttachments?: GenerateFilesOptions["customPomAttachments"];
    projectRoot?: GenerateFilesOptions["projectRoot"];
    customPomDir?: GenerateFilesOptions["customPomDir"];
    customPomImportAliases?: GenerateFilesOptions["customPomImportAliases"];
    customPomImportNameCollisionBehavior?: GenerateFilesOptions["customPomImportNameCollisionBehavior"];
    testIdAttribute?: GenerateFilesOptions["testIdAttribute"];
    generateFixtures?: GenerateFilesOptions["generateFixtures"];
    routeMetaByComponent?: Record<string, RouteMeta>;
    vueRouterFluentChaining?: boolean;
  } = {},
): Promise<GeneratedFileOutput[]> {
  const projectRoot = options.projectRoot ?? process.cwd();
  const entries = Array.from(componentHierarchyMap.entries())
    .sort((a, b) => a[0].localeCompare(b[0]));

  const views = entries.filter(([, d]) => d.isView);
  const components = entries.filter(([, d]) => !d.isView);

  const makeAggregatedContent = (
    header: string,
    outputDir: string,
    items: Array<[string, IComponentDependencies]>,
  ) => {
    const imports: string[] = [];
    const generatedClassNames = new Set(items.map(([name]) => name));

    if (!basePageClassPath) {
      throw new Error("basePageClassPath is required for aggregated generation");
    }

    // Aggregate mode goal: consolidate all generated POM classes into one file.
    // Instead of inlining BasePage/Pointer helpers and stripping imports via regex, we
    // emit/copy those dependencies into the output folder and import them normally.
    //
    // This keeps output deterministic and avoids fragile source rewriting.
    const runtimeDirRel = "./_pom-runtime";
    const runtimeClassGenRel = `${runtimeDirRel}/class-generation`;

    imports.push(`import type { PwLocator, PwPage } from "${runtimeClassGenRel}/playwright-types";`);
    imports.push(`import { BasePage } from "${runtimeClassGenRel}/BasePage";`);
    imports.push(`import type { Fluent } from "${runtimeClassGenRel}/BasePage";`);
    imports.push(`export * from "${runtimeDirRel}/click-instrumentation";`);
    imports.push(`export * from "${runtimeClassGenRel}/playwright-types";`);
    imports.push(`export * from "${runtimeClassGenRel}/Pointer";`);
    imports.push(`export * from "${runtimeClassGenRel}/BasePage";`);

    const customPomImportResolution = resolveCustomPomImportResolution(generatedClassNames, projectRoot, {
      customPomDir: options.customPomDir,
      customPomImportAliases: options.customPomImportAliases,
      customPomImportNameCollisionBehavior: options.customPomImportNameCollisionBehavior,
    });
    const customPomClassIdentifierMap = customPomImportResolution.classIdentifierMap;
    const customPomMethodSignaturesByClass = customPomImportResolution.methodSignaturesByClass;
    const customPomAvailableClassIdentifiers = customPomImportResolution.availableClassIdentifiers;

    for (const importSpecifier of Object.values(customPomImportResolution.importSpecifiersByClass).sort((left, right) => left.exportName.localeCompare(right.exportName))) {
      const importPath = stripExtension(toPosixRelativePath(outputDir, importSpecifier.absolutePath));
      if (importSpecifier.localIdentifier !== importSpecifier.exportName) {
        imports.push(`import { ${importSpecifier.exportName} as ${importSpecifier.localIdentifier} } from "${importPath}";`);
        continue;
      }
      imports.push(`import { ${importSpecifier.exportName} } from "${importPath}";`);
    }

    // Collect any navigation return types referenced by generated methods so we can emit
    // stub classes when the destination view has no generated test ids (and therefore no
    // corresponding POM class in this file).
    const referencedTargets = new Set<string>();
    for (const [, deps] of items) {
      for (const dt of deps.dataTestIdSet) {
        if (dt.targetPageObjectModelClass) {
          referencedTargets.add(dt.targetPageObjectModelClass);
        }
      }
    }

    const stubTargets = Array.from(referencedTargets)
      .filter(t => !generatedClassNames.has(t))
      .sort((a, b) => a.localeCompare(b));

    const availableClassNames = new Set<string>([...generatedClassNames, ...stubTargets]);

    const depsByClassName = new Map<string, IComponentDependencies>(entries);

    const stubs = stubTargets.map(t =>
      (() => {
        const composed = getComposedStubBody(t, availableClassNames, depsByClassName, vueFilesPathMap, projectRoot);
        const body = composed?.lines ?? [
          "    constructor(page: PwPage) {",
          "        super(page);",
          "    }",
        ];

        return [
          "/**\n * Stub POM generated because it is referenced as a navigation target but\n * did not have any generated test ids in this build.\n */",
          `export class ${t} extends BasePage {`,
          ...body,
          "}",
        ].join("\n");
      })(),
    );

    const classes = items.map(([name, deps]) =>
      generateViewObjectModelContent(name, deps, componentHierarchyMap, vueFilesPathMap, basePageClassPath, {
        outputDir,
        outputStructure: "aggregated",

        customPomAttachments: options.customPomAttachments ?? [],
        customPomClassIdentifierMap,
        customPomAvailableClassIdentifiers,
        customPomMethodSignaturesByClass,
        testIdAttribute: options.testIdAttribute,
        vueRouterFluentChaining: options.vueRouterFluentChaining,
        routeMetaByComponent: options.routeMetaByComponent,
      }),
    );

    const baseContent = [
      header,
      ...imports,
      ...classes,
      ...(stubs.length ? ["", ...stubs] : []),
    ].filter(Boolean).join("\n\n");

    return baseContent;
  };

  const base = ensureDir(outDir);
  const outputFile = path.join(base, "page-object-models.g.ts");
  const header = `/// <reference lib="es2015" />\n${eslintSuppressionHeader}/**\n * Aggregated generated POMs\n${AUTO_GENERATED_COMMENT}`;
  const content = makeAggregatedContent(header, path.dirname(outputFile), [...views, ...components]);

  const indexFile = path.join(base, "index.ts");
  const indexContent = `${eslintSuppressionHeader}/**\n * POM exports\n${AUTO_GENERATED_COMMENT}\n\nexport * from "./page-object-models.g";\n`;
  const runtimeFiles = buildRuntimeGeneratedFiles(base, basePageClassPath);

  return [
    { filePath: outputFile, content },
    { filePath: indexFile, content: indexContent },
    ...runtimeFiles,
  ];
}

function createFile(filePath: string, content: string) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
  fs.writeFileSync(filePath, content);
}

function lowerFirst(value: string): string {
  if (!value)
    return value;
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function toPascalCaseLocal(str: string): string {
  const cleaned = (str ?? "")
    .replace(/\$\{[^}]*\}/g, " ")
    .replace(/[^a-z0-9]+/gi, " ")
    .trim();

  if (!cleaned)
    return "";

  return cleaned
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => {
      const preserveInternalCaps = /[a-z][A-Z]/.test(word);
      return preserveInternalCaps
        ? upperFirst(word)
        : upperFirst(word.toLowerCase());
    })
    .join("");
}

interface WidgetInstance {
  className: "ToggleWidget" | "CheckboxWidget";
  propertyName: string;
  testId: string;
}

function getWidgetInstancesForView(
  componentName: string,
  dataTestIdSet: Set<IDataTestId>,
  availableClassIdentifiers: Set<string>,
): WidgetInstance[] {
  const out: WidgetInstance[] = [];
  const usedPropNames = new Set<string>();

  const ensureUnique = (base: string) => {
    let candidate = base;
    let i = 2;
    while (usedPropNames.has(candidate)) {
      candidate = `${base}${i}`;
      i++;
    }
    usedPropNames.add(candidate);
    return candidate;
  };

  for (const dt of dataTestIdSet) {
    const raw = dt.value;

    // Skip keyed/dynamic test ids; instance fields can't represent those ergonomically.
    if (raw.includes("${")) {
      continue;
    }

    const toggleSuffix = "-toggle";
    const checkboxSuffix = "-checkbox";

    let className: WidgetInstance["className"] | null = null;
    let stem = "";

    if (raw.endsWith(toggleSuffix)) {
      className = "ToggleWidget";
      stem = raw.slice(0, -toggleSuffix.length);
    }
    else if (raw.endsWith(checkboxSuffix)) {
      className = "CheckboxWidget";
      stem = raw.slice(0, -checkboxSuffix.length);
    }
    else {
      continue;
    }

    if (!availableClassIdentifiers.has(className)) {
      continue;
    }

    // Prefer stripping the view prefix (e.g. PreferencesPage-) for cleaner member names.
    const viewPrefix = `${componentName}-`;
    const descriptorRaw = stem.startsWith(viewPrefix) ? stem.slice(viewPrefix.length) : stem;
    const descriptorPascal = toPascalCaseLocal(descriptorRaw);

    if (!descriptorPascal) {
      continue;
    }

    if (className === "ToggleWidget") {
      let base = descriptorPascal.replace(/Toggle$/i, "");

      // Ergonomic naming: if a toggle name contains an "Enable..." tail, prefer that tail.
      // Example: AppPreferencesEnableSessionEmails -> enableSessionEmailsToggle
      const enableIndex = base.indexOf("Enable");
      if (enableIndex > 0) {
        base = base.slice(enableIndex);
      }

      const propBase = lowerFirst(base);
      const propName = ensureUnique(propBase ? `${propBase}Toggle` : "toggle");
      out.push({ className, propertyName: propName, testId: raw });
      continue;
    }

    // Checkbox
    const base = descriptorPascal
      .replace(/CheckBox$/i, "")
      .replace(/Checkbox$/i, "");
    const propBase = lowerFirst(base);
    const propName = ensureUnique(propBase ? `${propBase}Checkbox` : "checkbox");
    out.push({ className, propertyName: propName, testId: raw });
  }

  return out;
}

function getComponentInstances(
  childrenComponent: Set<string>,
  componentHierarchyMap: Map<string, IComponentDependencies>,
  attachmentsForThisView: Array<{ className: string; propertyName: string }> = [],
  widgetInstances: WidgetInstance[] = [],
) {
  let content = "\n";

  for (const a of attachmentsForThisView) {
    content += `    ${a.propertyName}: ${a.className};\n`;
  }

  for (const w of widgetInstances) {
    content += `    ${w.propertyName}: ${w.className};\n`;
  }

  childrenComponent.forEach((child) => {
    if (componentHierarchyMap.has(child) && componentHierarchyMap.get(child)?.dataTestIdSet.size) {
      const childName = child.split(".vue")[0];
      content += `    ${childName}: ${childName};\n`;
    }
  });
  return `${content}\n`;
}

function getConstructor(
  childrenComponent: Set<string>,
  componentHierarchyMap: Map<string, IComponentDependencies>,
  attachmentsForThisView: Array<{ className: string; propertyName: string }> = [],
  widgetInstances: WidgetInstance[] = [],
  options?: { testIdAttribute?: string },
) {
  let content = "    constructor(page: PwPage) {\n";
  const attr = (options?.testIdAttribute ?? "data-testid").trim() || "data-testid";
  content += `        super(page, { testIdAttribute: ${JSON.stringify(attr)} });\n`;

  for (const a of attachmentsForThisView) {
    content += `        this.${a.propertyName} = new ${a.className}(page, this);\n`;
  }

  for (const w of widgetInstances) {
    content += `        this.${w.propertyName} = new ${w.className}(page, ${JSON.stringify(w.testId)});\n`;
  }

  childrenComponent.forEach((child) => {
    if (componentHierarchyMap.has(child) && componentHierarchyMap.get(child)?.dataTestIdSet.size) {
      const childName = child.split(".vue")[0];
      content += `        this.${childName} = new ${childName}(page);\n`;
    }
  });
  content += "    }";
  return `${content}\n`;
}
